In [2]:
import pandas as pd
import numpy as np

In [3]:
january_august2019 = pd.read_csv('January_August.csv')
september_march2020 = pd.read_csv('September_March2020.csv')

In [4]:
january_august2019.head()

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,...,CANCELLED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,1,1,2,F9,N216FR,292,11292,DEN,"Denver, CO",15304,...,0,206,235,1506,7,21,0,29,0,0
1,1,1,2,F9,N344FR,488,11292,DEN,"Denver, CO",14635,...,0,221,234,1607,7,0,0,16,0,5
2,1,1,2,F9,N211FR,1748,11109,COS,"Colorado Springs, CO",13204,...,0,207,260,1520,7,0,0,48,0,0
3,1,1,2,F9,N223FR,680,11292,DEN,"Denver, CO",13204,...,0,227,245,1546,7,0,0,18,0,0
4,1,1,2,AS,N613AS,128,11630,FAI,"Fairbanks, AK",14747,...,0,220,203,1533,7,19,0,0,0,0